// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwzezumuqgrtetjnwovh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3emV6dW11cWdydGV0am53b3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTMwNTgsImV4cCI6MjA2ODY2OTA1OH0.5nEVyBx-vmN-5z8wVo1k2XRMi-i8NnsTj07-OQ_Xx-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});